const Queue = require('./Queue')
const Deque = require('./Deque')

const queue = new Queue()
console.log(queue.isEmpty())

queue.enqueue('John')
queue.enqueue('Wick')
queue.enqueue('Dog')

console.log('toString', queue.toString())
console.log('size', queue.size())

queue.dequeue()
console.log('toString', queue.toString())

const deque = new Deque()
console.log(deque.isEmpty())
deque.addBack('John')
deque.addBack('Wick')
console.log(deque.toString())
deque.addBack('Dog')
console.log(deque.toString())
console.log(deque.size())
console.log(deque.isEmpty())
deque.removeFront()
console.log(deque.toString())
deque.removeBack()
console.log(deque.toString())
deque.addFront('John')
console.log(deque.toString())
